# app:
#   install: false
#   existingUrl: "http://0.0.0.0/5055"
rasax:
  tag: "1.1.0"
eventService:
  tag: "1.1.0"
dbMigrationService:
  tag: "1.1.0"
rasa:
  version: "3.1.0"
  tag: "3.1.0"
  versions:
    rasaProduction:
      enabled: true
      tag: "3.1.0"
    rasaWorker:
      enabled: true
      tag: "3.1.0"
